### ISSUE TITLE
Create IDCred Definition Error

### ISSUE THREAD

**Issue by bmarur** [ibm-datapower/datapower-configuration-manager#49] opened 2017-05-22 03:49 UTC
Hi Experts,

I'm testing out DCM definitions for our process automation, I encountered the below error while I run IdCred-from-definition on my custom ant Script.

**Command**:  ant -f custom_build.xml -Ddm.dir=. -Dhost=192.168.0.19 -Duid=bharath -Ddevice=dp01 -Denvironment=dp01 -Ddomain=udcDemo domain-create idcred-from-def save

idcred-from-def:
    [nxslt] nxslt running c:\Users\Bharath\Documents\Tools\dcm/src/remove-unwanted-elements.xsl on c:\Users\Bharath\Documents\Tools\ant_tutorials/ucdDemo/ucdDemo.idcred.dcm.xml producing tmp
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] nxslt running c:\Users\Bharath\Documents\Tools\dcm/src/idcred-to-ant.xsl on tmp producing c:\Users\Bharath\Documents\Tools\ant_tutorials\tmp/idcred.ant.xml
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] SystemId Unknown; Line #74; Column #28; This file doesn't contain a dcm:idcred element!
    [nxslt] SystemId Unknown; Line #76; Column #42; Failed to generate internal template due to errors listed above.
    [nxslt] (Location of error unknown)Stylesheet directed termination

I have attached the ANT Script and Definition File, Could you please look at it and let me know where I'm going wrong.

[ant_tutorials.zip](https://github.com/ibm-datapower/datapower-configuration-manager/files/1017684/ant_tutorials.zip)

Thanks,
Bharath

**Comment by pavanKumarMeduri** [comment] 2017-05-22 13:46
Hello **bmarur**,
I think you are doing automation of DataPower by using UCD with DCM and I am also trying the same thing.
Till now I was done with Domain level,Now I want to do the  Service level automation with DP by using ant script.
Cloud Please suggest me how you are doing and which procedure you are following.
Thank You

**Comment by nhmathis** [comment] 2017-05-22 15:47
Hi @bmarur,

I am seeing that it fails on the second DCM command: `idcred-from-def`

I'm not exactly certain why it's not failing earlier, but it looks like you are missing the `-Didcred.file` argument. 
https://github.com/ibm-datapower/datapower-configuration-manager/blob/master/deploy.ant.xml/#L771

I suggest your try to re-run your command with that argument set.

**Comment by pavanKumarMeduri** [comment] 2017-05-22 17:30
Hi @**nhmathis** ,
Currently I am working on Automation of DCM with Ant-Scripts,in that
I want to Deploy a service in Data Power from the Jenkins  by using the ANT Scripts.Do you have any Git repository URL regarding this task.
Please provide me some stuff regarding to it.
Thank you

**Comment by nhmathis** [comment] 2017-05-22 18:48
Hi @pavanKumarMeduri,

As I am a plugin developer for IBM UrbanCode, I personally have the most experience using the DCM Ant commands through the context of the DataPower plugin for UCD. In this model, Jenkins would push artifacts to UCD (using one of our Jenkins plugins) and then kick off a UCD process. This UCD process would then contain your DataPower steps to import/configure the DataPower server along with any necessary approval, notification, or other integration processes. 

With UCD out of the picture, you would have to implement this process manually through a script or set of sequential commands. Furthermore, you have to configure the DCM on each of your Jenkins build agents to be accessible. The [DataPower Wiki](https://github.com/ibm-datapower/datapower-configuration-manager/wiki) provides all currently available documentation on the DCM cli.

I must defer to the DataPower team for best practices on deploying to DataPower through a Jenkins-only approach.

**Comment by bmarur** [comment] 2017-05-22 19:33
Hi @nhmathis ,

I seem to get the same error while I run with -Didcred.file argument as well, I have given the full path however it is still failing with an error that 

**command**: ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=192.168.0.19 -Duid=bharath -Ddomain=Test_bmarur -Didcred.file="C:/Users/bharath/Documents/dcm/dcm/ucdDemo.idcred.dcm.xml" check-access idcred-from-def save

**PFB Logs**

`
Buildfile: C:\Users\bharath\Documents\dcm\dcm\deploy.ant.xml
-check-std-args:

check-access:

clean:
   [delete] Deleting directory C:\Users\bharath\Documents\dcm\dcm\tmp

-init-dir:
    [mkdir] Created dir: C:\Users\bharath\Documents\dcm\dcm\tmp

-check-std-args:

check-access:

idcred-from-def:
    [nxslt] nxslt running ./src/remove-unwanted-elements.xsl on C:/Users/bharath/Documents/dcm/dcm/ucdDemo.idcred.dcm.xml producing tmp
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] nxslt running ./src/idcred-to-ant.xsl on tmp producing C:\Users\bharath\Documents\dcm\dcm\tmp/idcred.ant.xml
    [nxslt] Warning:  The encoding 'UTF-8' is not supported by the Java runtime.
    [nxslt] Warning: encoding "UTF-8" not supported, using UTF-8
    [nxslt] SystemId Unknown; Line #74; Column #28; This file doesn't contain a dcm:idcred element!
    [nxslt] SystemId Unknown; Line #76; Column #42; Failed to generate internal template due to errors listed above.
    [nxslt] (Location of error unknown)Stylesheet directed termination

BUILD FAILED
C:\Users\bharath\Documents\dcm\dcm\deploy.ant.xml:799: The following error occurred while executing this line:
C:\Users\bharath\Documents\dcm\dcm\tmp\idcred.ant.xml:1: Premature end of file.

Total time: 1 second
`

**Question**: is UTF-8 encoded definitions file supported by DCM, I was wondering, This errors points out at encoding format of definitions file ?

I have attached the definitions file as well for your reference
[ucdDemo.idcred.dcm.xml.zip](https://github.com/ibm-datapower/datapower-configuration-manager/files/1020001/ucdDemo.idcred.dcm.xml.zip)



Please advise

Thanks,
Bharath

**Comment by bmarur** [comment] 2017-05-22 20:51
Hi @pavanKumarMeduri ,

I'm at the same level as well :) , To be very honest I'm looking at various features in DCM tool in order to make a definite approach for our deployment patterns. At this point in time, I'm stuck with this definitions errors, I would like to utilize the UCD plugin to integrate Source control along with DP deployment definitions and export files.

Thanks,
Bharath

**Comment by nhmathis** [comment] 2017-10-09 14:25
Original question resolved and secondary question is duplicate of #51 and #52

**Closed by nhmathis** 2017-10-09 14:25 UTC
