### ISSUE TITLE
Updating password in PasswordAlias object

### ISSUE THREAD

**Issue by sekhardutta** [ibm-datapower/datapower-configuration-manager#74] opened 2017-09-12 11:55 UTC
Hi Team
Could you please let me know if we can update password in existing PasswordAlias object using dcm ?

Thanks
Sekhar Dutta

**Comment by nhmathis** [comment] 2017-09-15 16:20
Hi, 

You can modify and delete host aliases through `host-alias-remove` and `host-alias-set`, but not password alias. 

However, this issues appears to be a duplicate of #73. All discussion should occur there.

**Closed by nhmathis** 2017-09-15 16:20 UTC
